
volumes:
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      device: /home/moojig12/data
  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      device: /home/moojig12/data

secrets:
  db_root_pass.txt:
    file: ./secrets/db_root_pass.txt
  db_pass.txt:
    file: ./secrets/db_pass.txt
  wp_admin_pass.txt:
    file: ./secrets/wp_admin_pass.txt
  wp_user_pass.txt:
    file: ./secrets/wp_user_pass.txt

networks:
  inception:
    name: inception
    # driver: bridge

services:
  nginx:
    build: 
      context: requirements/nginx/.
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    image: nginx:notlatest
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress:notlatest
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_pass.txt
      - wp_admin_pass.txt
      - wp_user_pass.txt
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass.txt
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_pass.txt
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_pass.txt
    env_file:
      - .env
    expose:
      - "9000"
    restart: unless-stopped
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb:notlatest
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
            - db_root_pass.txt
            - db_pass.txt
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass.txt
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass.txt
    env_file:
      - .env
    expose:
      - "3306"
    restart: unless-stopped