
# volumes:
#   wordpress:
#     name: wordpress
#     driver: local
#     driver_opts:
#       device: /home/moojig12/data
# mariadb:
#   name: database
#   driver: local
#   dripver_opts:
#     device: /home/moojig12/data

secrets:
  db_root_pass.txt:
    file: ./secrets/db_root_pass.txt
  db_pass.txt:
    file: ./secrets/db_pass.txt
  wp_admin_pass.txt:
    file: ./secrets/wp_admin_pass.txt
  wp_user_pass.txt:
    file: ./secrets/wp_user_pass.txt

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    # image: nginx:42
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - ./web:/var/www/html
    restart: unless-stopped
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    # image: wordpress:42
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    secrets:
      - db_pass.txt
      - wp_admin_pass.txt
      - wp_user_pass.txt
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass.txt
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_pass.txt
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_pass.txt
    env_file:
      - .env
    expose:
      - "9000"
    restart: unless-stopped
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    volumes:
      - ./database:/var/lib/mysql
    secrets:
            - db_root_pass.txt
            - db_pass.txt
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass.txt
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass.txt
    env_file:
      - .env
    expose:
      - "3306"
    restart: unless-stopped