
# volumes:
#   wordpress:
#     name: wordpress2
#     driver: local
#     driver_opts:
#       device: /home/moojig12/data


services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    # image: nginx:42
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/var/www/html
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    # image: wordpress:42
    volumes:
      - ./web:/var/www/html