-- CREATE DATABASE IF NOT EXISTS wordpress ;
-- CREATE USER IF NOT EXISTS '$db_user'@'%' IDENTIFIED BY '$db_pass';
-- GRANT ALL PRIVILEGES ON *.* TO '$db_user'@'%' WITH GRANT OPTION;
-- FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS $db1_name ;
CREATE USER IF NOT EXISTS '$db1_user'@'%' IDENTIFIED BY '$db1_pwd' ;
GRANT ALL PRIVILEGES ON $db1_name.* TO '$db1_user'@'%' ;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345' ;
FLUSH PRIVILEGES;